name: Lint

on:
  push:
    paths-ignore:
      - '*.md'
      - '**/*.md'
      - 'docs/**.*'
    branches:
      - master
      - development**
  pull_request:
    paths-ignore:
      - '*.md'
      - '**/*.md'
      - 'docs/**.*'
    types:
      - opened
      - edited
      - synchronize

jobs:
  flake8:
    runs-on: ubuntu-latest
    container:
      image: "python"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint using Flake8
        run: |
          flake8 --count --show-source --statistics
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
