name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: python:3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt

      - name: Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Get the tag name
        if: ${{false}}
        run: echo "TAG=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Generate changelog
        if: ${{false}}
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ env.TAG }}
          path: ./CHANGELOG.md

      - name: Upload release assets & changelog
        if: ${{false}}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
